services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev-container
    working_dir: /workspace
    tty: true
    stdin_open: true
    volumes:
      - ./:/workspace # bind mount: container changes reflect to local
    ports:
      - '8501:8501' # streamlit default port
      - '5173:5173' # vite/svelte default dev port
    command: ['bash'] # container does not auto-start services
